# Generated by Django 2.2.7 on 2019-12-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('userkey', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10000)),
            ],
        ),
    ]
