# Generated by Django 2.2.7 on 2019-12-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicpystroke', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('userkey', models.CharField(max_length=6)),
                ('password', models.CharField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
