# Generated by Django 2.2.7 on 2019-12-07 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicpystroke', '0002_auto_20191206_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdatas',
            name='userkey',
        ),
    ]
