# Generated by Django 2.2.7 on 2019-12-07 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicpystroke', '0003_remove_userdatas_userkey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdatas',
            old_name='username',
            new_name='Email1',
        ),
        migrations.RenameField(
            model_name='userdatas',
            old_name='password',
            new_name='Password1',
        ),
    ]
