# Generated by Django 2.2.7 on 2019-12-08 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicpystroke', '0004_auto_20191206_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdatas',
            old_name='Email1',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='userdatas',
            old_name='Password1',
            new_name='Password',
        ),
    ]
